### ISSUE TITLE
Make A PPA for easier adoption

### ISSUE THREAD

**Issue by kokizzu** [griddb/c_client#12]
most of ubuntu users uses apt-get anyway

**Comment by knonomura** [comment]
Thank you for you comment.

Currently we are publishing DEB file for Ubuntu on not only GitHub but also OpenSUSE Build Service.
https://github.com/griddb/c_client/blob/master/DEB-README.md

$ sudo sh -c "echo 'deb https://download.opensuse.org/repositories/home:/oanhltk/xUbuntu_18.04/ /' > /etc/apt/sources.list.d/home:oanhltk.list"
$ sudo apt-get update
$ sudo apt-get install griddb-c-client

**Comment by kokizzu** [comment]
got GPG error NO_PUBKEY if using that

**Comment by knonomura** [comment]
I'm sorry, but could you try the following method ?

<pre>
sudo sh -c "echo 'deb http://download.opensuse.org/repositories/home:/oanhltk/xUbuntu_18.04/ /' > /etc/apt/sources.list.d/home:oanhltk.list"
wget -nv https://download.opensuse.org/repositories/home:oanhltk/xUbuntu_18.04/Release.key -O Release.key
sudo apt-key add - < Release.key
sudo apt-get update
sudo apt-get install griddb-c-client
</pre>

https://software.opensuse.org/download/package?project=home:oanhltk&package=griddb-c-client

**Comment by kokizzu** [comment]
it worked :3

**Comment by knonomura** [comment]
I modified "(A) Using apt-get command" in DEB-README.md by 4eb529efd90dbbaa3a69f5031a6e3f047a28e138.
Thank you.
