### ISSUE TITLE
Fatal error: Uncaught TypeError:

### ISSUE THREAD

**Issue by ogzhntnrvr** [griddb/c_client#20]
Fatal error: Uncaught TypeError: count(): Argument #1 ($var) must be of type Countable|array, null given in C:\xampp\htdocs\MARKA\MARKA.php:54 Stack trace: #0 {main} thrown in C:\xampp\htdocs\MARKA\MARKA.php on line 54

**Comment by knonomura** [comment]
I close this issue as it is not related to griddb/c_client repository.
