### ISSUE TITLE
ilandan.net

### ISSUE THREAD

**Issue by totemuss** [griddb/c_client#29]
Web ilan sektöründe lider olmaya aday ilandan.net sitesi;
 Emlak vasıta ve alışveriş alanında aradığınızı kolayca bulabileceğiniz sizi yüz binlerce ilanla karşılayacak devamlı gelişen ve büyüyen bir platform olacak.

 [Emlak](https://ilandan.net/kategori-1-emlak.html?sayfa=1) alanında; yeni ve ikinci el konutları birbirinden farklı güzel daireler , müstakil evler, rezidanslar vedaha bir çok konutun yanında arsalar tarlalar ve işyerleri fabrikalar devren satılık ve kiralık işyerleri bulabilirsiniz.

 [Vasıta](https://ilandan.net/kategori-46-vasita.html?sayfa=1) bölümünde; yeni ve 2,el otomobiller arazi araçları ve ticari araçların yanı sıra vasıtaların diğer gereksinimleri hasarlı araçları ve yedek parçaları bulabilirsiniz. Motorsıkletler atvler temizlik ve bakım hizmetleri de var.
 İş makineleri ve yedek parça ilanları da var.

  [Alışveriş](https://ilandan.net/kategori-48-alisveris.html?sayfa=1) bölümünde; farklı kategorilerde ilanlar mevcuttur. Ev aletleri bilgisayarlar ve elektronik ürünlerde var. Ayrıca antika ve ikinci el ürünlerin ilanlarını da bulabilirsiniz.

 https://ilandan.net/ Farklı derslerde ders verenler ve özel ders arayanlarda var.
 İş ilanları iş arayanlar iş verenler ilgi alanlarına göre ayrılmış ve belli kriterlere ayrılmış sınıflandırılmış olarak yayınlanan ilanlar mevcut.

**Comment by knonomura** [comment]
Your issue is opened in griddb/c_client repository,
but I guess it is another topic.

**Comment by knonomura** [comment]
I close this issue as it is not related to griddb/c_client repository.
