### ISSUE TITLE
GUI for Telegram-bot

### ISSUE THREAD

**Issue by Makhm** [griddb/c_client#30]
import tkinter
from tkinter import Tk, Label, Entry, Button, Frame
from tkinter.scrolledtext import ScrolledText as TextArea
from tkinter import WORD
from database import Database
from functools import partial

class Main:
    WORK = True

    def __init__(self):
        self.__root = Tk()
        self.__root.title("Редактор Сhess Guider")
        self.__root.resizable(False, False)

        self.__figures_frame = Frame(self.__root)
        self.__guides_frame = Frame(self.__root)

        self.load_figures()
        self.load_guides()

        self.__root.mainloop(0)

    def load_figures(self):
        self.__figures_frame.destroy()
        self.__figures_frame = Frame(self.__root)
        self.__figures = {
            figure[1]: [Label(self.__figures_frame, text=figure[1]),
                        Button(self.__figures_frame, text="Редактировать", bg='yellow', command=partial(self.open_figure_editor, figure[0])),
                        Button(self.__figures_frame, text="Удалить", bg='red', command=partial(self.open_figure_deleter, figure[0]))]
            for figure in Database().get_all_figures()
        }

        for index, key in enumerate(self.__figures.keys()):
            self.__figures[key][0].grid(column=0, row=index+1, sticky='w')
            self.__figures[key][1].grid(column=1, row=index+1, sticky="w")
            self.__figures[key][2].grid(column=2, row=index+1, sticky="w")

        self.__figures_frame.grid(column=0, row=0, pady=5, padx=5, sticky="n")
        self.__new_figure = Button(self.__figures_frame, 
                                   text="Новая фигура", 
                                   fg="white", 
                                   bg='green', 
                                   command=partial(self.open_figure_editor, None))
        self.__new_figure.grid(column=0, row=0, columnspan=3,sticky='nesw')
        
    def load_guides(self):
        self.__guides_frame.destroy()
        self.__guides_frame = Frame(self.__root)
        self.__guides = {
            guide[1]: [Label(self.__guides_frame, text=guide[1]),
                        Button(self.__guides_frame, text="Редактировать", bg='yellow', command=partial(self.open_guide_editor, guide[0])),
                        Button(self.__guides_frame, text="Удалить", bg='red', command=partial(self.open_guide_deleter, guide[0]))]
            for guide in Database().get_all_guides()
        }

        for index, key in enumerate(self.__guides.keys()):
            self.__guides[key][0].grid(column=0, row=index+1, sticky='w')
            self.__guides[key][1].grid(column=1, row=index+1, sticky="w")
            self.__guides[key][2].grid(column=2, row=index+1, sticky="w")

        self.__guides_frame.grid(column=1, row=0, pady=5, padx=5, sticky="n")
        self.__new_guide = Button(self.__guides_frame, 
                                   text="Новый гайд", 
                                   fg="white", 
                                   bg='green', 
                                   command=partial(self.open_guide_editor, None))
        self.__new_guide.grid(column=0, row=0, columnspan=3,sticky='nesw')
        
    def open_figure_editor(self, figure_id):
        if self.WORK:
            self.WORK = False
            FigureEdit(figure_id)
            self.load_figures()
            self.WORK = True

    def open_figure_deleter(self, figure_id):
        if self.WORK:
            self.WORK = False
            FigureDelete(figure_id)
            self.load_figures()
            self.WORK = True

    def open_guide_editor(self, guide_id):
        if self.WORK:
            self.WORK = False
            GuideEdit(guide_id)
            self.load_guides()
            self.WORK = True
    
    def open_guide_deleter(self, guide_id):
        if self.WORK:
            self.WORK = False
            GuideDelete(guide_id)
            self.load_guides()
            self.WORK = True

class FigureEdit:
    def __init__(self, figure_id=None):
        self.__figure_id = figure_id
        if self.__figure_id is not None:
            self.__figure_name = Database().get_figure(figure_id)[1]
            self.__figure_definition = Database().get_figure(figure_id)[2]
        else:
            self.__figure_name = None
            self.__figure_definition = None

        self.__root = Tk()
        self.__root.title("Редактор фигуры Сhess Guider")
        self.__root.resizable(False, False)

        self.__window = Frame(self.__root)
        self.__button_frame = Frame(self.__window)
        self.__name_label = Label(self.__window, text="Название: ")
        self.__name_field = Entry(self.__window, width=40)
        self.__definition_label = Label(self.__window, text="Описание: ")
        self.__definition_field = TextArea(self.__window, width=58, height=10, wrap=WORD)
        self.__save_button = Button(self.__button_frame, text="Сохранить", bg="green", fg="white", command=self.save)
        self.__cancel_button = Button(self.__button_frame, text="Отмена", bg="red", fg="white", command=self.__root.destroy)

        self.__window.grid(column=0, row=0, pady=5, padx=5)
        self.__button_frame.grid(column=0, row=2, columnspan=2, sticky="e", pady=(5, 0))
        self.__name_label.grid(column=0, row=0, sticky="w")
        self.__name_field.grid(column=1, row=0, sticky="w")
        self.__definition_label.grid(column=0, row=1, sticky="n")
        self.__definition_field.grid(column=1, row=1)
        self.__save_button.grid(column=0, row=0)
        self.__cancel_button.grid(column=1, row=0)

        self.__name_field.insert(0, self.__figure_name if self.__figure_name is not None else "")
        self.__definition_field.insert(0.0, self.__figure_definition if self.__figure_definition is not None else "")

        self.__root.mainloop(1)

    def save(self):
        if self.__figure_id is not None:
            Database().del_figure(self.__figure_name)
        self.__figure_name = self.__name_field.get()
        self.__figure_definition = self.__definition_field.get("1.0", tkinter.END)
        Database().add_figure(self.__figure_name, self.__figure_definition, f_id=self.__figure_id)
        self.__root.destroy()

class FigureDelete:
    def __init__(self, figure_id):
        self.__figure_id = figure_id
        self.__figure_name = Database().get_figure(figure_id)[1]

        self.__root = Tk()
        self.__root.resizable(False, False)

        self.__window = Frame(self.__root)
        self.__text_lable = Label(self.__window, text=f"Удалить фигуру '{self.__figure_name}'?")
        self.__delete_button = Button(self.__window, text="Удалить", bg="red", fg="white", command=self.delete)
        self.__cancel_button = Button(self.__window, text="Отмена", bg="gray", fg="white", command=self.__root.destroy)

        self.__window.grid(column=0, row=0, pady=5, padx=5)
        self.__text_lable.grid(column=0, row=0,columnspan=2, sticky="e")
        self.__delete_button.grid(column=0, row=1,sticky='nesw')
        self.__cancel_button.grid(column=1, row=1,sticky='nesw')

        self.__root.mainloop(1)

    def delete(self):
        Database().del_figure(self.__figure_name)
        self.__root.destroy()

class GuideEdit:
    def __init__(self, guide_id=None):
        self.__guide_id = guide_id
        if self.__guide_id is not None:
            self.__guide_name = Database().get_guide(guide_id)[1]
            self.__guide_definition = Database().get_guide(guide_id)[2]
        else:
            self.__guide_name = None
            self.__guide_definition = None

        self.__root = Tk()
        self.__root.title("Редактор гайда Сhess Guider")
        self.__root.resizable(False, False)

        self.__window = Frame(self.__root)
        self.__button_frame = Frame(self.__window)
        self.__name_label = Label(self.__window, text="Название: ")
        self.__name_field = Entry(self.__window, width=40)
        self.__definition_label = Label(self.__window, text="Описание: ")
        self.__definition_field = TextArea(self.__window, width=58, height=10, wrap=WORD)
        self.__save_button = Button(self.__button_frame, text="Сохранить", bg="green", fg="white", command=self.save)
        self.__cancel_button = Button(self.__button_frame, text="Отмена", bg="red", fg="white", command=self.__root.destroy)

        self.__window.grid(column=0, row=0, pady=5, padx=5)
        self.__button_frame.grid(column=0, row=2, columnspan=2, sticky="e", pady=(5, 0))
        self.__name_label.grid(column=0, row=0, sticky="w")
        self.__name_field.grid(column=1, row=0, sticky="w")
        self.__definition_label.grid(column=0, row=1, sticky="n")
        self.__definition_field.grid(column=1, row=1)
        self.__save_button.grid(column=0, row=0)
        self.__cancel_button.grid(column=1, row=0)

        self.__name_field.insert(0, self.__guide_name if self.__guide_name is not None else "")
        self.__definition_field.insert(0.0, self.__guide_definition if self.__guide_definition is not None else "")

        self.__root.mainloop(1)

    def save(self):
        if self.__guide_id is not None:
            Database().del_guide(self.__guide_name)
        self.__guide_name = self.__name_field.get()
        self.__guide_definition = self.__definition_field.get("1.0", tkinter.END)
        Database().add_guide(self.__guide_name, self.__guide_definition, g_id=self.__guide_id)
        self.__root.destroy()

class GuideDelete:
    def __init__(self, guide_id):
        self.__guide_id = guide_id
        self.__guide_name = Database().get_guide(guide_id)[1]

        self.__root = Tk()
        self.__root.resizable(False, False)

        self.__window = Frame(self.__root)
        self.__text_lable = Label(self.__window, text=f"Удалить гайд '{self.__guide_name}'?")
        self.__delete_button = Button(self.__window, text="Удалить", bg="red", fg="white", command=self.delete)
        self.__cancel_button = Button(self.__window, text="Отмена", bg="gray", fg="white", command=self.__root.destroy)

        self.__window.grid(column=0, row=0, pady=5, padx=5)
        self.__text_lable.grid(column=0, row=0,columnspan=2, sticky="e")
        self.__delete_button.grid(column=0, row=1,sticky='nesw')
        self.__cancel_button.grid(column=1, row=1,sticky='nesw')

        self.__root.mainloop(1)

    def delete(self):
        Database().del_guide(self.__guide_name)
        self.__root.destroy()

Main()

**Comment by knonomura** [comment]
Your issue is opened in griddb/c_client repository,
but I guess it is another topic.

**Comment by knonomura** [comment]
I close this issue as it is not related to griddb/c_client repository.
